version: "3"
services:
  
  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - REDIS_HOST=order-redis-node-0
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
    command: >
      sh -c "while ! redis-cli -h order-redis-node-0 -a redis cluster info | grep -q 'cluster_state:ok'; do
        echo 'Waiting for Redis cluster to be ready...';
        sleep 5;
      done;
      gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app"
    depends_on:
      - order-redis-node-0
      - order-redis-node-1
      - order-redis-node-2
      - order-redis-node-3
      - order-redis-node-4
      - order-redis-node-5

  order-redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - order_redis_data_0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=order-redis-node-0 order-redis-node-1 order-redis-node-2 order-redis-node-3 order-redis-node-4 order-redis-node-5'

  order-redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - order_redis_data_1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=order-redis-node-0 order-redis-node-1 order-redis-node-2 order-redis-node-3 order-redis-node-4 order-redis-node-5'

  order-redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - order_redis_data_2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=order-redis-node-0 order-redis-node-1 order-redis-node-2 order-redis-node-3 order-redis-node-4 order-redis-node-5'

  order-redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - order_redis_data_3:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=order-redis-node-0 order-redis-node-1 order-redis-node-2 order-redis-node-3 order-redis-node-4 order-redis-node-5'

  order-redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - order_redis_data_4:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=order-redis-node-0 order-redis-node-1 order-redis-node-2 order-redis-node-3 order-redis-node-4 order-redis-node-5'

  order-redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - order_redis_data_5:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDISCLI_AUTH=redis'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=order-redis-node-0 order-redis-node-1 order-redis-node-2 order-redis-node-3 order-redis-node-4 order-redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

  stock-service:
    build: ./stock
    image: stock:latest
    environment:
      - REDIS_HOST=stock-redis-node-0
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
    command: >
      sh -c "while ! redis-cli -h stock-redis-node-0 -a redis cluster info | grep -q 'cluster_state:ok'; do
        echo 'Waiting for Redis cluster to be ready...';
        sleep 5;
      done;
      gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app"
    depends_on:
      - stock-redis-node-0
      - stock-redis-node-1
      - stock-redis-node-2
      - stock-redis-node-3
      - stock-redis-node-4
      - stock-redis-node-5

  stock-redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - stock_redis_data_0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=stock-redis-node-0 stock-redis-node-1 stock-redis-node-2 stock-redis-node-3 stock-redis-node-4 stock-redis-node-5'

  stock-redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - stock_redis_data_1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=stock-redis-node-0 stock-redis-node-1 stock-redis-node-2 stock-redis-node-3 stock-redis-node-4 stock-redis-node-5'

  stock-redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - stock_redis_data_2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=stock-redis-node-0 stock-redis-node-1 stock-redis-node-2 stock-redis-node-3 stock-redis-node-4 stock-redis-node-5'

  stock-redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - stock_redis_data_3:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=stock-redis-node-0 stock-redis-node-1 stock-redis-node-2 stock-redis-node-3 stock-redis-node-4 stock-redis-node-5'

  stock-redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - stock_redis_data_4:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=stock-redis-node-0 stock-redis-node-1 stock-redis-node-2 stock-redis-node-3 stock-redis-node-4 stock-redis-node-5'

  stock-redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - stock_redis_data_5:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDISCLI_AUTH=redis'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=stock-redis-node-0 stock-redis-node-1 stock-redis-node-2 stock-redis-node-3 stock-redis-node-4 stock-redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

  payment-service:
    build: ./payment
    image: user:latest
    environment:
      - REDIS_HOST=payment-redis-node-0
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
    command: >
      sh -c "while ! redis-cli -h payment-redis-node-0 -a redis cluster info | grep -q 'cluster_state:ok'; do
        echo 'Waiting for Redis cluster to be ready...';
        sleep 5;
      done;
      gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app"
    depends_on:
      - payment-redis-node-0
      - payment-redis-node-1
      - payment-redis-node-2
      - payment-redis-node-3
      - payment-redis-node-4
      - payment-redis-node-5

  payment-redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - payment_redis_data_0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=payment-redis-node-0 payment-redis-node-1 payment-redis-node-2 payment-redis-node-3 payment-redis-node-4 payment-redis-node-5'

  payment-redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - payment_redis_data_1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=payment-redis-node-0 payment-redis-node-1 payment-redis-node-2 payment-redis-node-3 payment-redis-node-4 payment-redis-node-5'

  payment-redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - payment_redis_data_2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=payment-redis-node-0 payment-redis-node-1 payment-redis-node-2 payment-redis-node-3 payment-redis-node-4 payment-redis-node-5'

  payment-redis-node-3:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - payment_redis_data_3:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=payment-redis-node-0 payment-redis-node-1 payment-redis-node-2 payment-redis-node-3 payment-redis-node-4 payment-redis-node-5'

  payment-redis-node-4:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - payment_redis_data_4:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDIS_NODES=payment-redis-node-0 payment-redis-node-1 payment-redis-node-2 payment-redis-node-3 payment-redis-node-4 payment-redis-node-5'

  payment-redis-node-5:
    image: docker.io/bitnami/redis-cluster:7.4
    volumes:
      - payment_redis_data_5:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=redis'
      - 'REDISCLI_AUTH=redis'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=payment-redis-node-0 payment-redis-node-1 payment-redis-node-2 payment-redis-node-3 payment-redis-node-4 payment-redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

volumes:
  order_redis_data_0:
    driver: local
  order_redis_data_1:
    driver: local
  order_redis_data_2:
    driver: local
  order_redis_data_3:
    driver: local
  order_redis_data_4:
    driver: local
  order_redis_data_5:
    driver: local
  stock_redis_data_0:
    driver: local
  stock_redis_data_1:
    driver: local
  stock_redis_data_2:
    driver: local
  stock_redis_data_3:
    driver: local
  stock_redis_data_4:
    driver: local
  stock_redis_data_5:
    driver: local
  payment_redis_data_0:
    driver: local
  payment_redis_data_1:
    driver: local
  payment_redis_data_2:
    driver: local
  payment_redis_data_3:
    driver: local
  payment_redis_data_4:
    driver: local
  payment_redis_data_5:
    driver: local
