apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  selector:
    component: order
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: order
  template:
    metadata:
      labels:
        component: order
    spec:
      containers:
        - name: order
          image: order:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5000", "app:app"]
          ports:
            - containerPort: 5000
          env:
            - name: GATEWAY_URL
              value: "http://192.168.49.2"
            - name: USER_SERVICE_URL
              value: "user-service"
            - name: STOCK_SERVICE_URL
              value: "stock-service"
            - name: REDIS_SENTINEL_HOST
              value: "order-redis-sentinel"
            - name: REDIS_SENTINEL_PORT
              value: "26379"
            - name: REDIS_MASTER_SET
              value: "order-redis"
            - name: REDIS_PASSWORD
              value: "redis"
            - name: REDIS_DB
              value: "0"